title: "Hi, I'm Max Hartman"
theme: jekyll-theme-minimal
logo: "/images/1699229207438.jpg"

social_media:
  github: MaxBHartman
  linkedin: hartmanmax

# Other settings
baseurl: ""
url: "https://maxbhartman.github.io"
